name: Build documentation tex file

on: [workflow_dispatch]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

#      - name: Explain why this job ran
#        run: |
#          /bin/echo "The ${{ github.event_name }} event triggered this step."

      - name: compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: docs/
          latexmk_use_lualatex: true

#      - name: upload compiled pdf
#        uses: actions/upload-artifact@v3
#        with:
#          name: 

      - name: upload pdf to repo
        run: |
          git config --global user.name "Hannah Mark"
          git config --global user.email "hfmark@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add docs/main.pdf
          git commit -m "update documentation"
          git push
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
