name: Build gravgui

#on: [push]

on: [workflow_dispatch]

#on:
#  workflow_run:
#    workflows: ["Your Workflow Name"]
#    types:
#      - manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: conda install gtk3
      run: |
          $CONDA/bin/conda install -c conda-forge gtk3

    - name: Configure and build project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: gravgui
        path: build/gravgui

