name: Build gravgui for ubuntu

#on: [push]

on: [workflow_dispatch]

#on:
#  workflow_run:
#    workflows: ["Your Workflow Name"]
#    types:
#      - manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install libgtk-3-dev
      run: |
          sudo apt install libgtk-3-dev

    - name: window functions
      run: |
        /usr/bin/gcc -I. -c window_functions.c

    - name: filter windows
      run: |
        /usr/bin/g++ -O3 -I. -std=c++11 -c filt.cpp

    - name: make gravgui
      run: |
        /usr/bin/g++ -O3 -I. -std=c++11 gravgui.cpp filt.o window_functions.o -lm $(pkg-config --cflags --libs gtk+-3.0) -o gravgui

    - name: package stuff
      run: |
        chmod +x gravgui
        mkdir linux-download
        mv gravgui linux-download/
        cp -r database linux-download/
        cp style.css linux-download/

    - name: Upload zipped executable and deps
      uses: actions/upload-artifact@v3
      with:
        name: gravgui-lin
        path: linux-download/

