name: Build gravgui for ubuntu

#on: [push]

on: [workflow_dispatch]

#on:
#  workflow_run:
#    workflows: ["Your Workflow Name"]
#    types:
#      - manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install libgtk-3-dev
      run: |
          sudo apt install libgtk-3-dev

    - name: make everything
      run: |
        make

    - name: package stuff
      run: |
        chmod +x gravgui
        mkdir linux-download
        mv gravgui linux-download/
        cp -r database linux-download/
        cp style.css linux-download/

    - name: Upload zipped executable and deps
      uses: actions/upload-artifact@v3
      with:
        name: gravgui-lin
        path: linux-download/

