name: Build gravgui for mac

#on: [push]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install gtk libraries and cross fingers
      run: |
          brew install gtk+3

    - name: install make
      run: |
          brew install make

    - name: install gcc?
      run: |
          brew install gcc

    - name: make things
      run: |
          make

    - name: package stuff
      run: |
        mkdir macos-download
        mv gravgui macos-download/
        cp -r database macos-download/
        cp style.css macos-download/

    - name: Upload zipped executable and deps
      uses: actions/upload-artifact@v3
      with:
        name: gravgui-mos
        path: macos-download/

