name: Build gravgui for mac

#on: [push]

on: [workflow_dispatch]

#on:
#  workflow_run:
#    workflows: ["Your Workflow Name"]
#    types:
#      - manual

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install gtk libraries and cross fingers
      run: |
          brew install gtk+3

#    - name: Configure and build project
#      run: |
#        mkdir build
#        cd build
#        cmake -D CMAKE_C_COMPILER=/usr/bin/gcc -D CMAKE_CXX_COMPILER=/usr/bin/g++ ..
#        make

    - name: build the other way
      run: |
        /usr/bin/gcc -I. -c window_functions.c
        /usr/bin/g++ -O3 -I. -std=c++11 -c filt.cpp
        /usr/bin/g++ -O3 -I. -std=c++11 gravgui.cpp filt.o window_functions.o -lm $(pkg-config --cflags --libs gtk+-3.0) -o gravgui

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: gravgui-mos
        #path: build/gravgui
        path: gravgui

