name: Build gravgui for windows

#on: [push]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: set up MSYS2 UCRT64
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-gtk3
            mingw-w64-ucrt-x86_64-pkg-config
            make

    - name: Checkout repository
      uses: actions/checkout@v4

    - shell: msys2 {0}
      run: |
        make

    - name: package stuff
      run: |
        mkdir windows-download
        mv gravgui.exe windows-download/
        cp -r database windows-download/
        cp style.css windows-download/

    - name: Upload zipped executable and deps
      uses: actions/upload-artifact@v3
      with:
        name: gravgui-win
        path: windows-download/

